[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "gtts>=2.5.4",
    "moviepy>=2.1.2",
    "pydub>=0.25.1",
]
